project_id = "xxxkqyfelhihipptghsm"

[functions.analyze-medical-photo]
verify_jwt = false

[functions.track-visit]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.register-partner]
verify_jwt = false

[functions.notify-admin-order]
verify_jwt = false
